Add `include": ["./src"],` to the sample-tsconfig.json (#199)
This tells typescript to only care about files in ./src, and now exclude ./dist and ./webpack.conf.js.

Before this, I sometimes get errors like this from `tsc` and vscode ide

```
~/ic-projects/mobin  master ✗                                       6h45m ⚑  ⍉
▶ ./node_modules/.bin/tsc -b
error TS5055: Cannot write file '/Users/bengo/ic-projects/mobin/dist/mobin_assets/index.js' because it would overwrite input file.

error TS5055: Cannot write file '/Users/bengo/ic-projects/mobin/webpack.config.js' because it would overwrite input file.


Found 2 errors.
```